name: >-
  Publish a dev release (prerelease) on a selected branch.

on:
  # Run by manual trigger
  workflow_dispatch:
    inputs:
      base-branch:
        description: >-
          The base branch that a dev release will be based.
        required: true
      pre-id:
        description: >-
          The pre-release identifier.
        required: true
        default: 'dev'
jobs:
  main_job:
    runs-on: ubuntu-latest
    name: main job
    steps:
      - name: create dev release branch
        id: create-branch
        uses: fortinet/github-action-version-branch@1.0.0
        with:
          base-branch: ${{ github.event.inputs.base-branch }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          name-prefix: devrel_
          version-level: 'prerelease'
          pre-id: ${{ github.event.inputs.pre-id }}
      # checkout the release branch
      - name: checkout dev release branch
        uses: actions/checkout@v2
        with:
          # set ref to the head branch (newly created) from the output of step: create-branch
          ref: ${{ steps['create-branch'].outputs['head-branch'] }}
      # configure the commit author for the version bump commit
      # use the github-bot account
      - name: config commit author (bot)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      # install all dependencies
      - name: install project dependencies
        run: npm ci
      # bump version by running `npm version`
      - name: bump version
        id: bump-version
        # use the head version from the output of step: create-branch
        # use allow-same-version option
        run: npm version ${{ steps['create-branch'].outputs['head-version'] }} --allow-same-version
      - name: push changes
        # push commits only. Even though a tag is created, it will not be pushed.
        run: git push
      - name: build project
        run: npm run build
      # prepare release assets
      - name: make release assets
        run: npm run make-release
      # create a release
      - id: create-release
        name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps['create-branch'].outputs['head-version'] }} # Use the output from the `create-branch` step
          release_name: ${{ steps['create-branch'].outputs['head-version'] }} # Use the output from the `create-branch` step
          draft: false
          prerelease: ${{ steps['create-branch'].outputs['is-prerelease'] == 'true' }} # Use the output from the `create-branch` step
      - id: upload-release-asset
        name: upload release assets
        uses: svenstaro/upload-release-action@2.2.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps['create-branch'].outputs['head-version'] }} # Use the output from the `create-branch` step
          prerelease: ${{ steps['create-branch'].outputs['is-prerelease'] == 'true' }} # Use the output from the `create-branch` step
          file: ./release/*
          file_glob: true
          overwrite: true
